services:
  testldap:
    image: osixia/openldap
    container_name: ${SHIBBOLETH_CONTAINER_NAME}
    env_file: 
      - ${ENV_DIR}shibboleth
    environment:
      LDAP_LOG_LEVEL: "256"
    #   LDAP_ORGANISATION: "DAACS INC"
    #   LDAP_DOMAIN: "daacs.net"
    #   OPENLDAP_BOOTSTRAP_SUFFIX: "dc=daacs,dc=net"
    #   LDAP_BASE_DN: "daacs.net"
    #   LDAP_ADMIN_PASSWORD: "donkey"
    #   LDAP_CONFIG_PASSWORD: "config"
    #   LDAP_READONLY_USER: "false"
    #   #LDAP_READONLY_USER_USERNAME: "readonly"
    #   #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "false"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_VERIFY_CLIENT: "demand"
    #   LDAP_REPLICATION: "false"
    #   #LDAP_REPLICATION_CONFIG_SYNCPROV: 'binddn="cn=admin,cn=config" bindmethod=simple credentials="$$LDAP_CONFIG_PASSWORD" searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical'
    #   #LDAP_REPLICATION_DB_SYNCPROV: 'binddn="cn=admin,$$LDAP_BASE_DN" bindmethod=simple credentials="$$LDAP_ADMIN_PASSWORD" searchbase="$$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical'
    #   #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
    #   # KEEP_EXISTING_CONFIG: "true"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "3893:389"
      - "6363:636"
    # For replication to work correctly, domainname and hostname must be
    # set correctly so that "hostname"."domainname" equates to the
    # fully-qualified domain name for the host.
    domainname: "daacs.net"
    hostname: "ldap-server"


    # VIRTUAL_HOST=ldap.victor.com docker compose -f docker-compose.yml up -d 
    # docker compose -f docker-compose.yml up -d 

# https://github.com/osixia/container-openldap/blob/main/image/service/slapd/startup.sh
    # works and this is where we start from
    # ldapsearch -x -H ldap://localhost -b dc=daacs,dc=net -D "cn=admin,dc=daacs,dc=net" -w admin

    # ldapsearch -x -h ldap://a4fe49b05eac -p 3892 -b dc=daacs,dc=net -D "cn=admin,dc=daacs,dc=net" -w admin

    # works but going to delete.
    # ldapsearch -x -H ldap://localhost -b dc=example,dc=org -D "cn=admin,dc=daacs,dc=net" -w admin