FROM node:latest

RUN apt-get update && apt-get -y install cron vim 

#create cron file
RUN touch /etc/cron.d/export-cron

#Adding Cron commands to file
RUN <<EOF 
ls -l

echo '# must be ended with a new line (Unix) and not CRLF (Windows)
0 0 * * * export $(xargs -0 -a /proc/1/environ); cd /usr/src/app && node upload_to_spaces.js >> /var/log/cron.log
# An empty line is required at the end of this file for a valid cron file. 

' >> /etc/cron.d/export-cron

EOF

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/export-cron

# Apply cron job
RUN crontab /etc/cron.d/export-cron
 
# Create the log file to be able to run tail
RUN touch /var/log/cron.log

# Run the command on container startup
CMD cron && tail -f /var/log/cron.log
