services:
  #backup_service_name:
    restart: unless-stopped
    image: daacs-backup-cron
    networks:
      - myNetwork
    env_file: 
      - ${MONGO_ENV_DIR}webserver-mongo
      - ${BACKUP_ENV_DIR}digitalocean
    volumes:
      - "${FOLDER_START}:/usr/src/app"
    build: 
      context: .
      dockerfile: $DIR/Dockerfile-export

networks:
  myNetwork:
    external: true
