FROM node:latest

RUN apt-get update && apt-get -y install cron vim 

# Copy hello-cron file to the cron.d directory
COPY ./docker_copy/export-cron /etc/cron.d/export-cron
 
# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/export-cron

# Apply cron job
RUN crontab /etc/cron.d/export-cron
 
# Create the log file to be able to run tail
RUN touch /var/log/cron.log
 
# Run the command on container startup
CMD cron && tail -f /var/log/cron.log