version: "3.3"

services:
  backupdata:
    restart: unless-stopped
    networks:
      - myNetwork
    env_file: 
      - ../env-prod/.env-prod-webserver-mongo
      - ../env-prod/.env-prod-digitalocean
    volumes:
      - "/var/www/html/${FOLDER_START}:/usr/src/app"
    build: 
      context: .
      dockerfile: ./Dockerfile-export

networks:
  myNetwork:
    external: true
