FROM node:22.23.0-bookworm

RUN apt-get update && apt-get -y install cron vim 

RUN curl -fsSL https://pgp.mongodb.com/server-7.0.asc | gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor 


RUN echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-7.0.list

RUN apt-get update && apt-get install -y mongodb-database-tools && apt-get install zip -y

#create cron file
RUN touch /etc/cron.d/export-cron

#Adding Cron commands to file
RUN <<EOF 
ls -l

echo '# must be ended with a new line (Unix) and not CRLF (Windows)
0 0 * * * export $(xargs -0 -a /proc/1/environ); cd /usr/src/app && node upload_to_spaces.js >> /var/log/cron.log
# An empty line is required at the end of this file for a valid cron file. 

' >> /etc/cron.d/export-cron

EOF

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/export-cron

# Apply cron job
RUN crontab /etc/cron.d/export-cron
 
# Create the log file to be able to run tail
RUN touch /var/log/cron.log

# Run the command on container startup
# CMD cron && tail -f /var/log/cron.log

CMD ["/bin/sh", "-c", "cron && tail -f /var/log/cron.log" ]

