services:
  #backup_service_name:
    restart: unless-stopped
    networks:
      - myNetwork
    env_file: 
      - ${ENV_DIR}webserver-mongo
      - ${ENV_DIR}digitalocean
    volumes:
      - "${FOLDER_START}:/usr/src/app"
    build: 
      context: .
      dockerfile: ./Dockerfile-export

networks:
  myNetwork:
    external: true
