services:
  #backup_service_name:
    restart: unless-stopped
    image: daacs-backup-cron
    networks:
      - myNetwork
    environment:
      MONGODB_IS_SSL: "${MONGODB_IS_SSL}"
    env_file: 
      - ${MONGO_ENV_DIR}webserver-mongo
      - ${BACKUP_ENV_DIR}digitalocean
    volumes:
      - "${FOLDER_START}:/usr/src/app"
      - "${MONGODB_DB_CERT_PATH}/mongodb.crt:/mongodb.crt"
      - "${MONGODB_DB_CERT_PATH}/mongodb.pem:/mongodb.pem"

networks:
  myNetwork:
    external: true
