FROM mongo:latest
RUN apt-get update && apt-get install vim -y
WORKDIR /home/
COPY mongodb-prod.conf mongod.conf
COPY run-prod.sh /home/run.sh
#COPY run-dev.sh /home/run-dev.sh
#COPY run-prod.sh /home/run-prod.sh
RUN chmod +x /home/*.sh
ENTRYPOINT ["/bin/bash", "/home/run.sh"]