storage:
  dbPath: /data/db
#  engine:
#  wiredTiger:

net:
  port: 27017
  bindIp: 0.0.0.0
  tls:
    mode: requireTLS
    certificateKeyFile: /home/mongodb.pem
    CAFile: /home/mongodb.crt
    disabledProtocols: "TLS1_0,TLS1_1"
    # tlsUseSystemCA: true  <-- Remove this line

# how the process runs
processManagement:
  timeZoneInfo: /usr/share/zoneinfo

