# This is a reserved spot for most properties containing passwords or other secrets.
# Created by install at 2025-12-30T03:48:47.280564128Z

# Access to internal AES encryption key
idp.sealer.storePassword =ipB6Juhiy5QyZjPj2GlmvayDSmsM9sOp
idp.sealer.keyPassword =ipB6Juhiy5QyZjPj2GlmvayDSmsM9sOp

# Password for idp-backchannel.p12 
idp.backchannel.keyStorePassword =Svtm0nh7U5xJV3cpj3HCZ1mL8EijMJ7H

# Default access to LDAP authn and attribute stores. 
idp.authn.LDAP.bindDNCredential              =woofwoof
idp.attribute.resolver.LDAP.bindDNCredential =%{idp.authn.LDAP.bindDNCredential:undefined}

# Salt used to generate persistent/pairwise IDs, must be kept secret
#idp.persistentId.salt =changethistosomethingrandom
