services:
  shibboleth_real:
    expose:
      - 80
      - 443
    restart: unless-stopped
    networks:
      - myNetwork
    # env_file: 
    #   - ${ENV_DIR}shibboleth
    environment:
      - "VIRTUAL_HOST=${VIRTUAL_HOST}"
      - "SHIBBOLETH_CONTAINER_NAME=${SHIBBOLETH_CONTAINER_NAME}"
      - "ENTITY_ID=${ENTITY_ID}"
      - "SHIBBOLETH_SCOPE=${SHIBBOLETH_SCOPE}"
      - "LDAP_URL=${LDAP_URL}"
      - "LDAP_BASE_DN=${LDAP_BASE_DN}"
      - "LDAP_BIND_DN=${LDAP_BIND_DN}"
      - "LDAP_DN_FORMAT=${LDAP_DN_FORMAT}"
      - "LDAP_TLS=${LDAP_TLS}"
      - "LDAP_USE_SSL=${LDAP_USE_SSL}"
      - "LDAP_BIND_PASSWORD=${LDAP_BIND_PASSWORD}"
    # volumes:
    #   - "${FOLDER_START}:/usr/src/app"
    image: shibbolethreal

networks:
  myNetwork:
    external: true
