FROM jwilder/nginx-proxy:latest
RUN apt update && apt install vim -y
COPY nginx/compress.conf /etc/nginx/conf.d
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/default_location /etc/nginx/vhost.d/default_location