version: "3.3"

services:
  mongoqserverdev:
    image: mongo
    restart: unless-stopped 
    env_file: 
      - ../env-dev/.env-dev-queuemongo-init
      - ../env-dev/.env-dev-queuemongo
      - ../env-dev/.env-dev-oauth
    networks:
      - myNetwork
    ports:
      - ${MONGODB_MAPPED_PORT}:27017
    volumes:
      - ./mongodb/mongo-queue-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    container_name: ${MONGODB_CONTAINER_NAME}

  qserverdev:
    restart: unless-stopped
    image: daacs-qserver
    build: 
      context: .
      dockerfile: ./Dockerfile-queue-dev.debian
    env_file: 
      - ../env-dev/.env-dev-queueserver
      - ../env-dev/.env-dev-queuemongo
      - ../env-dev/.env-dev-oauth
      - ../env-dev/.env-dev-email
    command: >
      /bin/sh -c "cd /usr/src/app/ && chmod +x lightsidetest.sh && ./lightsidetest.sh && cd /usr/src/app && npm run-script dev"
    expose:
      - 80
      - 443
    networks:
      - myNetwork
    volumes:
      - "/var/www/html/${FOLDER_START}:/usr/src/app"
    container_name: ${WEBSERVER_CONTAINER_NAME}

networks:
  myNetwork:
    external: true