version: "3.3"

#mongo_service_name:
  devmongo:
    image: mongo
    restart: unless-stopped
    env_file: 
      - ../env-dev/.env-dev-webserver-mongo-init
      - ../env-dev/.env-dev-webserver-mongo
      - ../env-dev/.env-dev-oauth
    networks:
      - myNetwork
    ports:
      - ${MONGODB_MAPPED_PORT}:27017
    volumes:
      - ./mongodb/assessments-media-self-hosted.json:/docker-entrypoint-initdb.d/assessments-final.json
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    container_name: ${MONGODB_CONTAINER_NAME}

  #webserver_service_name:
    command: >
        /bin/sh -c "cd /usr/src/app && npm run-script start-dev --prefix=./DAACS-Webserver"
    expose:
      - ${PORT}
      - 443
    restart: unless-stopped
    networks:
      - myNetwork
    env_file: 
      - ../env-dev/.env-dev-webserver
      - ../env-dev/.env-dev-webserver-mongo
      - ../env-dev/.env-dev-oauth
      - ../env-dev/.env-dev-memcached
      - ../env-dev/.env-dev-email
    volumes:
      - "/var/www/html/${FOLDER_START}:/usr/src/app"
    image: node
    deploy:
      mode: replicated
      replicas: ${REPLICAS}

networks:
  myNetwork:
    external: true