version: "3.3"

services:
  devproductionmongo:
    image: mongo
    restart: unless-stopped
    env_file: 
      - ../env-prod-dev/.env-prod-webserver-mongo-init
      - ../env-prod-dev/.env-prod-webserver-mongo
      - ../env-prod-dev/.env-prod-oauth
    networks:
      - myNetwork
    ports:
      - ${MONGODB_MAPPED_PORT}:27017
    volumes:
      - ./mongodb/assessments/:/docker-entrypoint-initdb.d/assessments/
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    container_name: ${MONGODB_CONTAINER_NAME}

  devproductionwebserver:
    command: >
        /bin/sh -c "cd /usr/src/app && npm run-script start-production --prefix=./DAACS-Webserver"
    expose:
      - ${PORT}
      - 443
    restart: unless-stopped
    networks:
      - nginx-proxy
      - myNetwork
    env_file: 
      - ../env-prod-dev/.env-prod-webserver
      - ../env-prod-dev/.env-prod-webserver-mongo
      - ../env-prod-dev/.env-prod-oauth
      - ../env-prod-dev/.env-prod-email
    volumes:
      - "/var/www/html/${FOLDER_START}:/usr/src/app"
    image: node
    deploy:
      mode: replicated
      replicas: ${REPLICAS}

networks:
  nginx-proxy:
    external: true
  myNetwork:
    external: true
